#!/bin/sh
sudo modprobe v4l2loopback exclusive_caps=1 video_nr=1
#ffmpeg -re -stream_loop -1 -i $1 -s:v 1280x720 -f v4l2 /dev/video1
ffmpeg -re -stream_loop -1 -i $1 -s:v 1280x920 -f v4l2 /dev/video1
