#!/bin/sh
if [ $# -eq 0 ]; then
    >&2 echo "Usage: ffa2i <audio file> <image file>"
    exit 1
fi

NAME=$(echo "$2" | awk -F'.' '{print $1}')
ffmpeg \
    -loop 1 \
    -i "$2" -i "$1" \
    -vf scale="iw/2:ih/2" \
    -c:v libx264 -pix_fmt yuv420p \
    -c:a aac -b:a 256k -ar 44100 \
    -preset faster -tune stillimage \
    -shortest -max_interleave_delta 500M \
    -movflags +faststart \
    "$NAME.mp4"
