#!/bin/sh
C='\033[1;34m'
G='\033[1;33m'
B='\033[0;30m'
#C="\033[1;3$(( $RANDOM * 6 / 32767 + 1 ))m"
NC='\033[0m'

echo -e "$B .o()()o.  ${C}$USER$NC"
echo -e "$B.o'    'o.  ${C}os${NC}  popbobOS"
echo -e "$B'O $G.  .$B O'  ${C}up${NC}  $(uptime -p | cut -c 4-)"
echo -e "$B  ·____·    ${C}pk${NC}  $(pacman -Q | wc -l)"
echo ""
