#!/bin/sh

if ! pgrep -x "mpd" > /dev/null
then
    mpd &
fi

mpd_discord_richpresence --no-idle &
ncmpcpp
killall ncmpcpp > /dev/null
killall mpd_discord_richpresence > /dev/null
killall mpd > /dev/null
