#!/bin/sh
# https://medium.com/analytics-vidhya/how-i-put-my-mind-under-version-control-24caea37b8a5

VAULT="$HOME/archive/notes"

cd $VAULT

git pull

# Exit prematurely if no changes to push
ANY_CHANGES="$(git status --porcelain | wc -l)"
if [ "$ANY_CHANGES" -eq 0 ]; then
    exit 0
fi

git pull
git add .
git commit -q -m "Synced at $(date +"%Y-%m-%d %H:%M:%S")"
git push -q
