#! /bin/sh

sxhkd &
$HOME/.dots/scripts/setup/init-xrandr.sh
$HOME/.dots/scripts/setup/init-polybar.sh

bspc monitor DP-4 -d I II III IV V VI
bspc monitor HDMI-0 -d VII VIII IX

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Program Rules
bspc rule -a Chromium desktop='^1'
bspc rule -a discord desktop='^7' state=fullscreen focus=off
bspc rule -a obs state=floating
bspc rule -a mpv desktop='^2' state=fullscreen
bspc rule -a MultiMC5 state=floating
