#! /bin/sh

sxhkd &
$HOME/.dots/scripts/setup/init-xrandr.sh
$HOME/.dots/scripts/setup/init-polybar.sh
$HOME/.dots/scripts/setup/init-autostart.sh

bspc monitor DP-4 -d I II III IV V VI
bspc monitor HDMI-0 -d VII VIII IX

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle       true
bspc config gapless_monocle      true

# Program Rules
bspc rule -a Chromium desktop='^1'
bspc rule -a discord desktop='^9' state=fullscreen focus=off
bspc rule -a obs state=floating
bspc rule -a MultiMC5 state=floating
bspc rule -a Steam state=floating
